### ISSUE TITLE
Output is missing fields from conditional groups

### ISSUE THREAD

**Issue by paralaxsd** [dearimgui/dear_bindings#28]
Hi,
I found that for recent commits of `dear_bindings`, generated .json files will miss field entries that are enclosed in conditional groups. One example for that is the following excerpt from the `ImGuiIO` struct (v1.89.1):

```c
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    void*       ImeWindowHandle;                // = NULL           // [Obsolete] Set ImGuiViewport::PlatformHandleRaw instead. Set this to your HWND to get automatic IME cursor positioning.
#else
    void*       _UnusedPadding;                                     // Unused field to keep data structure the same size.
#endif
```

The json output of dearbindings is now missing the corresponding metadata:
```json
{
    "names": [
        {
            "name": "ImeWindowHandle",
            "is_array": false
        }
    ],
    "type": {
        "declaration": "void*"
    },
    "comments": {
        "attached": "// = NULL           // [Obsolete] Set ImGuiViewport::PlatformHandleRaw instead. Set this to your HWND to get automatic IME cursor positioning."
    },
    "conditionals": [
        {
            "condition": "ifndef",
            "expression": "IMGUI_DISABLE_OBSOLETE_FUNCTIONS"
        }
    ]
},
{
    "names": [
        {
            "name": "_UnusedPadding",
            "is_array": false
        }
    ],
    "type": {
        "declaration": "void*"
    },
    "comments": {
        "attached": "// Unused field to keep data structure the same size."
    },
    "conditionals": [
        {
            "condition": "ifdef",
            "expression": "IMGUI_DISABLE_OBSOLETE_FUNCTIONS"
        }
    ]
},
```

I bisected the issue and found that it is first introduced at feef033. 
I hope that helps! :)

**Comment by ShironekoBen** [comment]
Very well spotted! Sorry, yeah - I forgot about that case when fixing another bug where struct field lists incorrectly included fields from nested types, and the resulting code was overenthusiastic about not including anything it didn't think was a direct child of the struct being emitted.

Thanks very much for tracking that down - should hopefully be fixed now!

**Comment by paralaxsd** [comment]
Perfect, can confirm that this fixes the regression.
Thanks for the super quick fix!
