### ISSUE TITLE
Unrecognized element when generating bindings for OpenGL3 backend

### ISSUE THREAD

**Issue by shawnhatori** [dearimgui/dear_bindings#50]
Here's the output for `python dear_bindings\dear_bindings.py --backend imgui\backends\imgui_impl_opengl3.h -o cimgui_impl_opengl3`:
```
Dear Bindings: parse Dear ImGui headers, convert to C and output metadata.
Parsing [path]\imconfig.h
Parsing [path]\imgui_impl_opengl3.h
Unrecognised element LexToken(LOGICALAND,'&&',50,2831)
Unrecognised element LexToken(LOGICALAND,'&&',50,2831)
Storing unmodified DOM
Applying modifiers
Writing output to cimgui_impl_opengl3[.h/.cpp/.json]
Done
```

**Comment by ShironekoBen** [comment]
Oh, interesting - the preprocessor condition parser didn't cope with line continuations so it was failing to parse a `#ifdef` that split across two lines. I've fixed that and it seems to generate sensible output now.
Thanks!

**Comment by shawnhatori** [comment]
Can confirm this error has been fixed, thanks!
