### ISSUE TITLE
Support for ImGui test engine?

### ISSUE THREAD

**Issue by JamesWrigley** [dearimgui/dear_bindings#60]
Hey there, would you be open to extending this library to provide bindings for the ImGui test engine? Or is it strictly meant for ImGui alone?

**Comment by ocornut** [comment]
I don’t have an answer for this myself, But I think I wouldn’t want to burden Ben with this, at least it seems pretty far out in my assumption about priorities:
- getting imgui_internal to a nice state
- getting popular extensions like implot working

Test Engine by nature would be naturally aimed at standardizing its API so events may be recorded into data files, so I imagine it may come with its own specialized solution.

**Comment by JamesWrigley** [comment]
Thanks, that makes sense :+1: I wasn't aware that support for implot etc was planned too, that sounds interesting.

**Comment by ocornut** [comment]
Well its not explicitly planned but the intent is that any similarly formatted file could easily be parsed and converted the same way, and implot would be obviously the strongest contender for it.
