### ISSUE TITLE
Add PLY to repository?

### ISSUE THREAD

**Issue by ocornut** [dearimgui/dear_bindings#72]
According to https://github.com/dabeaz/ply:
> Although PLY is open-source, it is not distributed or installed by package manager. There are only two files: lex.py and yacc.py, both of which are contained in a ply package directory. To use PLY, copy the ply directory into your project and import lex and yacc from the associated ply subpackage. Alternatively, you can install these files into your working python using make install.

Since the ply/ folder is ~214 KB it might be added to repo?

That, or I suggest amend documentation:
```
[ply](https://www.dabeaz.com/ply/) (Python Lex-Yacc, v3.11 tested)
```
to
```
[ply](https://www.dabeaz.com/ply/) (Python Lex-Yacc, v3.11 tested). 
extract then run `python setup.py install` to install or copy `ply/` folder to `dear_bindings/`.
```

**Comment by ocornut** [comment]
The thing as a non-Python user is that I have zero knowledge about its ecosystem.
Since dear bindings presumably should be usable by everyone, I would amend the Readme to be maximally explicit

**Comment by ShironekoBen** [comment]
I've made the instructions in the readme a lot more explicit about this, so hopefully that should make it easier for anyone not too familiar with Python. I'm going to close this for now but feel free to re-open if there's anything else you spot that could do with improvement!

Thanks!
