### ISSUE TITLE
imconfig path error when generating backends

### ISSUE THREAD

**Issue by is-it-ayush** [dearimgui/dear_bindings#81]
Hi Everyone! I stumbled upon this problem when trying to generate backend files with `python dear_bindings.py --backend -o cimgui_impl_opengl3 ../imgui/backends/imgui_impl_opengl3.h`. The python script throws,
```sh
Dear Bindings: parse Dear ImGui headers, convert to C and output metadata.
Parsing /home/ayush/personal/otto-ext-libs/imgui/backends/imconfig.h
Exception during conversion:
Traceback (most recent call last):
  File "/home/ayush/personal/otto-ext-libs/dear_bindings/dear_bindings.py", line 732, in <module>
    convert_header(
  File "/home/ayush/personal/otto-ext-libs/dear_bindings/dear_bindings.py", line 108, in convert_header
    dom_root.add_child(parse_single_header(include_file, context))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ayush/personal/otto-ext-libs/dear_bindings/dear_bindings.py", line 64, in parse_single_header
    with open(src_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ayush/personal/otto-ext-libs/imgui/backends/imconfig.h'
```
For context, The directory structure for my project folder i.e. ` otto-ext-libs` looks like below and the cwd where the python script is executed is `./otto-ext-libs/dear_bindings`,
```
otto-ext-libs
│
├── dear_bindings
│   ├── BuildAllBindings.bat
│   ├── dear_bindings.py
│   ├── docs
│   ├── examples
│   ├── LICENSE.txt
│   ├── requirements.txt
│   └── src
└── imgui
    ├── backends
    ├── docs
    ├── examples
    ├── imconfig.h
    ├── imgui.cpp
    ├── imgui_demo.cpp
    ├── imgui_draw.cpp
    ├── imgui.h
    ├── imgui_internal.h
    ├── imgui_tables.cpp
    ├── imgui_widgets.cpp
    ├── imstb_rectpack.h
    ├── imstb_textedit.h
    ├── imstb_truetype.h
    ├── LICENSE.txt
    └── misc
```
The python script doesn't search in parent directory for `imconfig.h` file. The solution I found was to manually specify the imconfig path with `python dear_bindings.py --backend -o cimgui_impl_opengl3 ../imgui/backends/imgui_impl_opengl3.h --imconfig-path ../imgui/imconfig.h`. This works perfectly fine. Since the directory of backends in constant in upstream imgui repo, why not have the script search in the parent directory for this file? Currently the command specified in the readme for generating the backend i.e. `python dear_bindings.py --backend -o cimgui_impl_opengl3 ../imgui/backends/imgui_impl_opengl3.h` doesn't work and can lead to confusion.

**Comment by ShironekoBen** [comment]
Hi,

Thanks for the feedback - you're absolutely right, that's definitely a bit of a pitfall for new users.
I've modified the code so that if `--backend` is specified, it looks for `imconfig.h` in the parent directory instead.

Thanks!

**Comment by is-it-ayush** [comment]
Hey @ShironekoBen! Since the commit is pushed to `main`, I'm marking this issue as completed. Thank you!!🤞
