### ISSUE TITLE
Add support for imgui_internal.h

### ISSUE THREAD

**Issue by ocornut** [dearimgui/dear_bindings#9]
Untested but Ben mentions this is still WIP

**Comment by ZimM-LostPolygon** [comment]
Was this abandoned? If not, is there any way to test it out? Doesn't seem like headers for imgui_internal.h are generated as of now

**Comment by ocornut** [comment]
The idea is that you’d need to run dear bindings on this specific header rather than imgui.h.

It doesn’t work yet. IMHO this is the most important feature ahead but this is being developed in spare time. Feel free to help fixing things if you can. 

Extra thought: due to the nature of internals i guess the generator could be tweaked to not emit the non-Ex/Ex functions.

**Comment by ZimM-LostPolygon** [comment]
> Extra thought: due to the nature of internals i guess the generator could be tweaked to not emit the non-Ex/Ex functions.
> 

Had the same thought. The non-Ex/Ex split makes it right more annoying, since C# supports default arguments just fine, and the variant with implied default values won't probably even be referenced by the wrapper.

**Comment by ocornut** [comment]
Did you meant to close this? I guess it's part of #47 ?
When #47 makes progress it may make sense to enable it on CI ?

**Comment by ShironekoBen** [comment]
Closing this as #47 implements `imgui_internal.h` support now. We can (hopefully!) track any more specific problems that come up with it as other issues.
